In [1]:
!pip3 install python-binance

Defaulting to user installation because normal site-packages is not writeable
Collecting python-binance
  Downloading python_binance-1.0.25-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 833 kB/s ta 0:00:01
Requirement already satisfied: requests in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from python-binance) (2.32.3)
Collecting aiohttp
  Downloading aiohttp-3.11.10-cp39-cp39-macosx_11_0_arm64.whl (455 kB)
     |████████████████████████████████| 455 kB 937 kB/s eta 0:00:01
Collecting pycryptodome
  Downloading pycryptodome-3.21.0-cp36-abi3-macosx_10_9_universal2.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 55.6 MB/s eta 0:00:01
Collecting dateparser
  Downloading dateparser-1.2.0-py2.py3-none-any.whl (294 kB)
     |████████████████████████████████| 294 kB 798 kB/s eta 0:00:01
Collecting websockets
  Downloading websockets-14.1-cp39-cp39-macosx_11_0_arm64.whl (159 kB)
     |████████████████████████████████| 159 kB 1.1 MB/s eta 0:00:01
Requirement already satisfied: six in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-binance) (1.15.0)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.1.0-cp39-cp39-macosx_11_0_arm64.whl (29 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.5.0-cp39-cp39-macosx_11_0_arm64.whl (52 kB)
     |████████████████████████████████| 52 kB 1.2 MB/s eta 0:00:01
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Collecting yarl<2.0,>=1.17.0
  Downloading yarl-1.18.3-cp39-cp39-macosx_11_0_arm64.whl (92 kB)
     |████████████████████████████████| 92 kB 906 kB/s eta 0:00:01
Collecting async-timeout<6.0,>=4.0
  Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Collecting aiohappyeyeballs>=2.3.0
  Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl (14 kB)
Collecting propcache>=0.2.0
  Downloading propcache-0.2.1-cp39-cp39-macosx_11_0_arm64.whl (45 kB)
     |████████████████████████████████| 45 kB 1.2 MB/s eta 0:00:01
Requirement already satisfied: attrs>=17.3.0 in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from aiohttp->python-binance) (24.2.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from multidict<7.0,>=4.5->aiohttp->python-binance) (4.12.2)
Requirement already satisfied: idna>=2.0 in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from yarl<2.0,>=1.17.0->aiohttp->python-binance) (3.8)
Requirement already satisfied: pytz in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from dateparser->python-binance) (2024.1)
Collecting regex!=2019.02.19,!=2021.8.27
  Downloading regex-2024.11.6-cp39-cp39-macosx_11_0_arm64.whl (284 kB)
     |████████████████████████████████| 284 kB 1.0 MB/s eta 0:00:01
Collecting tzlocal
  Downloading tzlocal-5.2-py3-none-any.whl (17 kB)
Requirement already satisfied: python-dateutil in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from dateparser->python-binance) (2.9.0.post0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from requests->python-binance) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from requests->python-binance) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (from requests->python-binance) (2024.7.4)
Installing collected packages: propcache, multidict, frozenlist, yarl, tzlocal, regex, async-timeout, aiosignal, aiohappyeyeballs, websockets, pycryptodome, dateparser, aiohttp, python-binance
Successfully installed aiohappyeyeballs-2.4.4 aiohttp-3.11.10 aiosignal-1.3.2 async-timeout-5.0.1 dateparser-1.2.0 frozenlist-1.5.0 multidict-6.1.0 propcache-0.2.1 pycryptodome-3.21.0 python-binance-1.0.25 regex-2024.11.6 tzlocal-5.2 websockets-14.1 yarl-1.18.3
WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [2]:
!pip3 install python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in /Users/tp_mini/Library/Python/3.9/lib/python/site-packages (1.0.1)
WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

https://www.youtube.com/watch?v=ZiBBVYB5PuU

In [ ]:
import pandas as pd
# from dotenv import load_dotenv
# load_dotenv() => read files from local .env

In [4]:
import os
from binance.client import Client #type: ignore
# api_key = os.environ['Binance_api_key_test']
api_key = 'VOlqUinuDO9sUXcfrBVoRSalVvN1SOAwTRNEqFcMEf5zcOVAxWv9A24I6YdrzrQc'
api_serect = 'UOCRaG8CuB5QpDCJH4jy9owBN0OA04Xl5g2vwERjRaELG4YdFOedKyaYq5xTFe3d'
client = Client(api_key, api_serect, testnet=True)

In [7]:
import pandas as pd
tickers = client.get_all_tickers()
df = pd.DataFrame(tickers)

In [8]:
df

         symbol            price
0        ETHBTC       0.03818000
1        LTCBTC       0.00113700
2        BNBBTC       0.00683000
3       BTCUSDT  106163.69000000
4       ETHUSDT    4054.17000000
...         ...              ...
1252  LUMIAUSDT       2.01100000
1253     SCRBTC       0.00001168
1254   SCRFDUSD       1.23900000
1255     SCRTRY      43.32000000
1256   KAIAUSDT       0.27280000

[1257 rows x 2 columns]

In [13]:
import requests
import json

url = "https://api1.binance.com"
# url = "https://api.binance.com" # also works
api_call = "/api/v3/ticker/price"
headers = {"content-type": "application/json", "X-MBX-APIKEY": api_key}

response = requests.get(url+api_call, headers=headers)
response = json.loads(response.text)
df1 = pd.DataFrame(response)
df1

             symbol          price
0            ETHBTC     0.03815000
1            LTCBTC     0.00113300
2            BNBBTC     0.00683400
3            NEOBTC     0.00017040
4           QTUMETH     0.00097700
...             ...            ...
2854  VELODROMEUSDT     0.21660000
2855       VANAUSDT    31.60000000
2856        VANABNB     0.04363000
2857      VANAFDUSD    31.66600000
2858        VANATRY  1106.90000000

[2859 rows x 2 columns]

In [23]:
from datetime import datetime, timedelta
client.ping() # Empty res means no error
server_time = client.get_server_time()
current_date = datetime.fromtimestamp(server_time['serverTime']/1000).strftime("%Y-%m-%d %H:%M:%S")
current_date

'2024-12-17 03:24:14'

In [40]:
import yfinance as yf
symbols = [i['symbol'] for i in tickers]


price_list = client.get_historical_klines("ETHBTC", interval='1d', start_str='2024-09-01')
data = pd.DataFrame(price_list)
data.columns = ['open_time','open', 'high', 'low', 'close', 'volume','close_time', 'qav','num_trades','taker_base_vol','taker_quote_vol', 'ignore']
data.index = [pd.to_datetime(x, unit='ms').strftime('%Y-%m-%d %H:%M:%S') for x in data.open_time]
usecols=['open', 'high', 'low', 'close', 'volume', 'qav','num_trades','taker_base_vol','taker_quote_vol']
data = data[usecols]
data = data.astype('float')

In [41]:
data

,open,high,low,close,volume,qav,num_trades,taker_base_vol,taker_quote_vol
2024-11-05 00:00:00,0.03549,0.03701,0.03484,0.03493,1007.6141,35.316636,13753.0,576.1998,20.213649
2024-11-06 00:00:00,0.03495,0.03637,0.03466,0.03601,2779.3702,98.111052,35043.0,1587.9530,56.056810
2024-11-07 00:00:00,0.03602,0.03826,0.03592,0.03814,2791.5394,104.945713,39320.0,1513.7430,56.907822
2024-11-08 00:00:00,0.03814,0.03880,0.03811,0.03870,2050.3349,78.765749,27807.0,1045.5154,40.173510
2024-11-09 00:00:00,0.03871,0.04409,0.03867,0.04080,2136.7874,84.994249,27115.0,1113.7831,44.337144
2024-11-10 00:00:00,0.04080,0.04086,0.03912,0.03965,2023.1945,81.201054,28568.0,1073.3064,43.084411
2024-11-11 00:00:00,0.03965,0.04103,0.03754,0.03810,1723.2606,66.818202,20490.0,961.1884,37.264949
2024-11-12 00:00:00,0.03809,0.04013,0.03664,0.03692,1181.1149,44.487344,8855.0,700.5449,26.385007
2024-11-13 00:00:00,0.03692,0.03720,0.03269,0.03524,1652.6445,59.336559,17694.0,941.4809,33.799978
2024-11-14 00:00:00,0.03523,0.04013,0.03464,0.03506,2039.9396,71.995656,25488.0,1185.4579,41.838790
2024-11-15 00:00:00,0.03504,0.03505,0.03358,0.03394,1278.8142,43.890992,14959.0,704.4998,24.192616
2024-11-16 00:00:00,0.03393,0.03522,0.03380,0.03460,912.1927,31.349800,10011.0,523.6898,17.995614
2024-11-17 00:00:00,0.03458,0.03482,0.03395,0.03423,1352.8973,46.467338,17508.0,736.6904,25.301267
2024-11-18 00:00:00,0.03422,0.03551,0.03382,0.03543,1713.5045,59.006308,21422.0,954.8360,32.869581
2024-11-19 00:00:00,0.03544,0.03562,0.03330,0.03372,1536.8506,52.269993,19389.0,820.3828,27.884188
2024-11-20 00:00:00,0.03372,0.03385,0.03237,0.03262,1447.4498,47.915593,17866.0,817.1013,27.057076
2024-11-21 00:00:00,0.03262,0.03457,0.03193,0.03417,2473.3094,82.642643,29863.0,1319.0741,44.027303
2024-11-22 00:00:00,0.03417,0.04105,0.03293,0.03365,1913.7838,64.624555,22337.0,1043.4040,35.255522
2024-11-23 00:00:00,0.03366,0.03537,0.03360,0.03475,1745.5149,60.160841,21235.0,916.8827,31.594943
2024-11-24 00:00:00,0.03475,0.03502,0.03401,0.03433,1149.2011,39.665087,15436.0,602.5579,20.807908
2024-11-25 00:00:00,0.03434,0.04488,0.03407,0.03669,1441.5174,51.065092,14786.0,872.2653,30.955912
2024-11-26 00:00:00,0.03671,0.03672,0.03527,0.03615,1235.3458,44.424700,14590.0,689.8524,24.814473
2024-11-27 00:00:00,0.03614,0.03833,0.03394,0.03824,2480.4941,92.037902,30149.0,1292.3255,47.926892
2024-11-28 00:00:00,0.03824,0.03824,0.03719,0.03740,2311.4084,87.094997,28627.0,1175.7678,44.293898
2024-11-29 00:00:00,0.03741,0.03746,0.03664,0.03689,1440.7410,53.355972,19381.0,747.8233,27.700001
2024-11-30 00:00:00,0.03689,0.03859,0.03686,0.03843,1574.7377,59.715916,22061.0,869.1444,32.968906
2024-12-01 00:00:00,0.03843,0.04336,0.03788,0.03811,1235.0530,47.262861,18775.0,715.7796,27.388274
2024-12-02 00:00:00,0.03810,0.03947,0.03760,0.03801,1377.3778,52.262391,20217.0,773.9362,29.372834
2024-12-03 00:00:00,0.03802,0.03811,0.03721,0.03773,1330.4471,50.242615,19593.0,692.6563,26.155566
2024-12-04 00:00:00,0.03772,0.04010,0.02600,0.03888,1709.1277,66.553082,22864.0,940.6391,36.661702
2024-12-05 00:00:00,0.03887,0.03956,0.03706,0.03907,2249.0373,86.153608,24981.0,1259.4714,48.216734
2024-12-06 00:00:00,0.03907,0.04102,0.03417,0.04013,2113.3400,84.163628,23801.0,1095.7502,43.624413
2024-12-07 00:00:00,0.04012,0.04030,0.03980,0.04006,810.4464,32.489047,12006.0,443.4834,17.778154
2024-12-08 00:00:00,0.04006,0.04452,0.03958,0.03960,830.5169,33.131046,11392.0,428.8359,17.108848
2024-12-09 00:00:00,0.03960,0.03985,0.03763,0.03808,1978.5143,77.313390,22161.0,1048.9553,41.003597
2024-12-10 00:00:00,0.03808,0.04259,0.01005,0.03756,2219.5022,84.126050,26154.0,1205.5872,45.672763
2024-12-11 00:00:00,0.03756,0.03796,0.03716,0.03787,2003.3345,75.546067,29692.0,871.6122,32.846330
2024-12-12 00:00:00,0.03787,0.03932,0.03782,0.03872,2205.2749,85.542225,28543.0,1035.0971,40.196659
2024-12-13 00:00:00,0.03872,0.03953,0.03842,0.03856,1568.1730,61.028898,22107.0,858.8265,33.423950
2024-12-14 00:00:00,0.03856,0.10000,0.03798,0.03812,1129.9903,43.538249,17433.0,585.3931,22.671882
2024-12-15 00:00:00,0.03811,0.04000,0.03745,0.03791,1288.5414,48.759288,17475.0,718.0440,27.165058
2024-12-16 00:00:00,0.03789,0.03828,0.03699,0.03812,1513.0566,56.968700,21265.0,798.5610,30.061143

In [48]:
import warnings
warnings.filterwarnings("ignore")
def penny_stock_range_breakout_2f(
        symbol='QBTS', 
        start='2024-09-01', 
        hold=20, 
        price_bo_period=60,
        vol_ma_period=20,
        vol_ratio=2.4):
    
    # qbts = yf.download(symbol, start=start, progress=False)
    price_list = client.get_historical_klines(symbol, interval='1d', start_str=start)
    data = pd.DataFrame(price_list)
    data.columns = ['open_time','Open', 'high', 'low', 'Close', 'Volume','close_time', 'qav','num_trades','taker_base_vol','taker_quote_vol', 'ignore']
    data.index = [pd.to_datetime(x, unit='ms').strftime('%Y-%m-%d %H:%M:%S') for x in data.open_time]
    usecols=['Open', 'high', 'low', 'Close', 'Volume', 'qav','num_trades','taker_base_vol','taker_quote_vol']
    data = data[usecols]
    qbts = data.astype('float')
    # Volume Surge
    condition_vol = []
    vol = qbts[['Volume']]
    vol['ma20'] = vol['Volume'].rolling(vol_ma_period).mean()
    vol['ratio'] = vol['Volume']/vol['ma20']
    for i in range(len(vol)):
        if vol['ratio'].iloc[i] >= vol_ratio:
            condition_vol.append(vol.index[i])

    # Price breakout 
    condition_price = []
    price = qbts[['Close']]
    price['Max'] = price['Close'].rolling(price_bo_period).max()
    price['Max'] = price['Max'].shift(2)
    for i in range(len(price)):
        if price['Max'].iloc[i] < price['Close'].iloc[i]:
            condition_price.append(price.index[i])

    # day of signal
    final = []
    first = 0
    for i in condition_vol:
        if i in condition_price:
            if first == 0: 
                first = i
                final.append(i)
            else:
                if (i - first).days >= 30:
                    first = i
                    final.append(i)
                else:
                    continue

    # Rate of success
    price_bt = qbts[['Open']]
    price_bt['Open_s20'] = price_bt['Open'].shift(-hold)
    price_bt['std'] = price_bt["Open"].pct_change().rolling(10).std()

    price_bt.ffill(inplace=True)
    price_bt['Entry'] = price_bt.apply(lambda x: 1 if x.name in final else 0, axis=1)
    price_bt['Entry'] = price_bt['Entry'].shift(1)
    price_bt_traded = price_bt[price_bt['Entry'] == 1]
    price_bt_traded['profit'] = price_bt_traded.apply(lambda x: x["Open_s20"]/x['Open']-1, axis=1)
    price_bt_traded['Symbol'] = symbol
    return price_bt_traded.iloc[:, [0, 1, 2, 4, 5]]

In [49]:
from tqdm import tqdm
df_list = []
for i in tqdm(symbols):
    df = penny_stock_range_breakout_2f(symbol=i)
    df_list.append(df)
pd.concat(df_list)

  5%|▌         | 63/1257 [00:07<01:54, 10.41it/s]